### ISSUE TITLE
Multicolor tables

### ISSUE THREAD

**Issue by AQueff** [mdahirel/PCItemplate#4]
Hi there, I tried to make my PCI Archaeo pdf today with the Rmarkdown template and got some issues. I am a not very familiar with GitHub so post it here, hope it is the good thing to do. Will make a new issue for each issue I found, since I managed to supress some errors by changing a bit my .rmd document, but I guess it is not the goal that authors have to change their code.

### First issue when I just copy/paste my code in the template : 
**error in the Rstudio window :** 
! Undefined control sequence.
<recently read> \cellcolor 

Erreur : LaTeX failed to compile manuscript.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See manuscript.log for more info.
De plus : Warning message:
In has_crop_tools() : 
Tool(s) not installed or not in PATH: ghostcript
-> As a result, figure cropping will be disabled.
Exécution arrêtée

**Error in the Latex log**
l.146 \cellcolor
                {gray!6}{Trinidad} & \cellcolor{gray!6}{TR-03} & \cellcolor{...

I guess this is because I used   kable_styling(full_width = FALSE, latex_options = "striped", font_size = 9) so that there are two different colors for seeing the lines better. But the gray used is not accepted by Latex apparently.

When I remove the latex_options = "striped" it goes further, I do not have this error again.

**Comment by mdahirel** [comment]
I was able to reproduce the error; this should be corrected in the current version of the template (works on my side at least)

**Comment by AQueff** [comment]
Thanks a lot to do this for the community.
