### ISSUE TITLE
Problem with tighlist

### ISSUE THREAD

**Issue by AQueff** [mdahirel/PCItemplate#5]
Here is the second problem:
when I remove the error about the color in table, another one blocks the knitting:

**Error in Rstudio:**
! Undefined control sequence.
l.188 \tightlist

Erreur : LaTeX failed to compile manuscript.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See manuscript.log for more info.
De plus : Warning message:
In has_crop_tools() : 
Tool(s) not installed or not in PATH: ghostcript
-> As a result, figure cropping will be disabled.
Exécution arrêtée

**Error in the Latex log:**
! Undefined control sequence.
l.188 \tightlist

This line 188 in the latex file contains a list indeed:
\begin{itemize}
\tightlist
\item
  the mineralogical determination of the raw material used by the Amerindians, mostly done by naked eye by untrained archaeologists
\item
  the quality of the reproduction of ancient photographs in scanned or photocopied documents
\item
  the lack of complete description of lapidary assemblages in most of the sites. The table or text of the articles may list tens of artifacts, while the figures only depict 5 of them.
\item
  the difficulty of assessing the origin of the artifacts in multicomponents archaeological sites
\item
  the difficulty of cultural attribution for ancient excavations
\end{itemize}

 which is in the rmd file:
The quality of information has been problematic for several topics of the database, including:

-   the mineralogical determination of the raw material used by the Amerindians, mostly done by naked eye by untrained archaeologists
-   the quality of the reproduction of ancient photographs in scanned or photocopied documents
-   the lack of complete description of lapidary assemblages in most of the sites. The table or text of the articles may list tens of artifacts, while the figures only depict 5 of them.
-   the difficulty of assessing the origin of the artifacts in multicomponents archaeological sites
-   the difficulty of cultural attribution for ancient excavations

I guess this type of list is "normal" and should work isn't it? Maybe remove \tightlist from the Latex? I do not find in the main.tex nor in the preamble.tex any call of a command that would put this \tightlist...

When I remove the list, the compilation goes further, see next issue :))

**Comment by mdahirel** [comment]
Can you check your config (RStudio version, `rmarkdown` package version, Pandoc version)? This problem has been documented and fixed a while ago in RStudio + `rmarkdown` (see https://github.com/rstudio/rmarkdown/issues/439 ).

As a demonstration, I have added a list to the Introduction of the template; the pdf knitted without any problem.

**Comment by AQueff** [comment]
I downloaded the test template for lists and indeed the list works well in your case.
I modified my own Rmarkdown document and added a blank line between each element of the list and it worked... a bit silly that the list crushes the compilation when it is 
- list1
- list2

and it works when it is
- list1

- list2
... 
Thanks

**Comment by mdahirel** [comment]
Re-opening to add that the list in the template wasn't actually a tightlist, and adding an actual tightlist actually recreates the error. But this is this time *actually* corrected as of last commit (warning: avoid using double spaces at the end of the line of a tightlist element, they will be interpreted as line breaks and create even "less tight" lists. You can try, this shouldn't break the pdf itself)
